config/routes.rb
Rails.application.routes.draw do
  get 'estaticas/contacto'

  get 'estaticas/nosotros'

  get 'home/index'
  root "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/estaticas_controller.rb
class EstaticasController < ApplicationController
  def contacto
    
  end

  def nosotros
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/estaticas_helper.rb
module EstaticasHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/estaticas/contacto.html.erb
<% provide(:titulo, "Contacto") %>
<h1>Página de contacto</h1>
<p>Aquí mostramos datos de contacto del blog</p>

<br>

<%= content_for :saludo, "Hola" %>
<%= yield :saludo %>

app/views/estaticas/nosotros.html.erb
<% provide(:titulo, "Nosotros") %>
<h1>Página sobre nosotros</h1>
<p>En esta página vamos a mostrar información sobre nosotros</p

app/views/home/index.html.erb
<% provide(:titulo, "Mi Blog") %>
<h1>Hola</h1>
<p>¡Bienvenidos a nuestro blog!</p>
<hr>
<p> Esta es la página de inicio</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:titulo) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/header' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_header.html.erb
<%= link_to 'Home', root_path %>
<%= link_to 'Contacto', estaticas_contacto_path %>
<%= link_to 'Nosotros', estaticas_nosotros_path %>